Repository msgpack/msgpack-java, pull requests merged in 2023-09, with the labels that each got.

#759 Update sbt to 1.9.4
  project/build.properties
Labels: library-update

#760 Update airframe-json, airspec to 23.8.6
  build.sbt
Labels: internal, library-update

#763 Update sbt to 1.9.6
  project/build.properties
Labels: library-update

#762 Update airframe-json, airspec to 23.9.1
  build.sbt
Labels: internal, library-update

#761 Update sbt-scalafmt to 2.5.2
  project/plugins.sbt
Labels: internal

#765 feature: Support JDK21 (and drop JDK7 support)
  .github/workflows/CI.yml
  build.sbt
  msgpack-core/src/main/java/org/msgpack/core/buffer/DirectBufferAccess.java
Labels: breaking, feature

#766 internal: Automatically generate release notes
  .github/release.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-note.yml
  README.md
Labels: internal, doc

#767 Update airframe-json, airspec to 23.9.2
  build.sbt
Labels: internal, library-update
