Repository msgpack/msgpack-java, pull requests merged in 2023-10, with the labels that each got.

#768 Add MessagePackMapper#handleBigIntegerAndBigDecimalAsString
  msgpack-jackson/README.md
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackMapper.java
  msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackMapperTest.java
Labels: doc

#769 Update airframe-json, airspec to 23.9.3
  build.sbt
Labels: internal, library-update

#772 Update airframe-json, airspec to 23.10.0
  build.sbt
Labels: internal, library-update

#770 use `setup-java` instead of deprecated `olafurpg/setup-scala`
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: deprecation

#773 Update sbt-osgi to 0.9.7
  project/plugins.sbt
Labels: internal

#771 Update jackson-databind to 2.15.3
  build.sbt
Labels: library-update

#774 Update sbt-osgi to 0.9.8
  project/plugins.sbt
Labels: internal

#775 Update sbt to 1.9.7
  project/build.properties
Labels: library-update

#776 add `dependabot.yml` for GitHub Actions update
  .github/dependabot.yml
Labels: internal
