Repository msgpack/msgpack-java, pull requests merged in 2023-07, with the labels that each got.

#745 Add `MessagePackMapper#handleBigDecimalAsString`
  msgpack-jackson/README.md
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackMapper.java
  msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackMapperTest.java
Labels: doc, feature

#741 Update sbt to 1.9.1
  project/build.properties
Labels: library-update

#746 Update sbt to 1.9.2
  project/build.properties
Labels: library-update

#744 Update airframe-json, airspec to 23.7.1
  build.sbt
Labels: internal, library-update

#748 Update airframe-json, airspec to 23.7.2
  build.sbt
Labels: internal, library-update

#750 Update sbt to 1.9.3
  project/build.properties
Labels: library-update
