Repository msgpack/msgpack-java, pull requests merged in 2023-02, with the labels that each got.

#711 Update jackson-databind to 2.14.2
  build.sbt
Labels: breaking

#714 update sbt script
  sbt
Labels: internal

#717 Update airframe-json, airspec to 23.2.5
  build.sbt
Labels: internal, library-update
