Repository msgpack/msgpack-java, pull requests merged in 2024-01, with the labels that each got.

#785 Fix fixint test in MessagePackTest.
  msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala
Labels: bug

#787 Remove dead code in MessagePacker.
  msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
Labels: internal

#786 Fix bug in ImmutableTimestampValueImpl.
  msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableTimestampValueImpl.java
Labels: bug

#790 Update sbt to 1.9.8
  project/build.properties
Labels: library-update

#789 Update sbt-osgi to 0.9.10
  project/plugins.sbt
Labels: internal

#791 Update airframe-json, airspec to 23.12.1
  build.sbt
Labels: internal, library-update

#792 Update airframe-json, airspec to 24.1.0
  build.sbt
Labels: internal, library-update

#788 Update jackson-databind to 2.16.1
  build.sbt
Labels: library-update

#794 Fix ClassCastException when array values is set as List
  msgpack-core/src/main/java/org/msgpack/value/Variable.java
Labels: bug

#796 Update sbt-osgi to 0.9.11
  project/plugins.sbt
Labels: internal
