Repository msgpack/msgpack-java, pull requests merged in 2025-07, with the labels that each got.

#895 Refactor CI to use matrix strategy and add JDK 24 support
  .github/workflows/CI.yml
Labels: feature

#899 Upgrade Scala to 3.7.1 and use Scala 3 code format style
  .scalafmt.conf
  CLAUDE.md
  README.md
  msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala
  msgpack-core/src/test/scala/org/msgpack/core/MessagePackerTest.scala
  msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
  msgpack-core/src/test/scala/org/msgpack/value/VariableTest.scala
Labels: doc

#900 Update README.md publishing instructions for Sonatype Central
  README.md
Labels: doc

#886 Update jackson-databind to 2.18.4
  build.sbt
Labels: library-update

#903 Fix Jackson deprecation warnings in MessagePackFactory
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackSerializerFactory.java
  msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Labels: bug
