Repository msgpack/msgpack-java, pull requests merged in 2025-02, with the labels that each got.

#872 Update airframe-json, airspec to 2025.1.1
  build.sbt
Labels: internal, library-update

#871 Update scala-collection-compat to 2.13.0
  build.sbt
Labels: internal, library-update

#869 Update sbt-scalafmt to 2.5.4
  project/plugins.sbt
Labels: internal

#868 Add support for jackson field ids
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
  msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
  msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatForFieldIdTest.java
Labels: feature
